color0 #484551
color1 #ffb4ab
color2 #c9bfff
color3 #c9c2e9
color4 #ffade4
color5 #c9bfff
color6 #c9c2e9
color7 #e5e1e9
color8 #938f9c
color9 #ffb4ab
color10 #c9bfff
color11 #c9c2e9
color12 #ffade4
color13 #c9bfff
color14 #c9c2e9
color15 #e5e1e9

cursor                #e5e1e9
cursor_text_color     #141318
background            #141318
foreground            #e5e1e9
selection_foreground  #c9c4d2
selection_background  #484551
active_border_color   #c9bfff
inactive_border_color #484551
url_color             #c9bfff

active_tab_foreground   #302273
active_tab_background   #c9bfff
inactive_tab_foreground #c9c4d2
inactive_tab_background #484551
cursor_trail_color      #c9c4d2
